### PR TITLE
Memory consumption predictability on prune action

### PR DESCRIPTION
**Pull request by vitalyzhakov**
Memory limit is set to 128M by default in php .
If I will be new user, I will take an error and may search another plugin to use.

Another purpose is to have plugin without forgetting to set memory limit after update.

### CODE REVIEW

**Comment by vitalyzhakov** [comment]
@joshp23 , hello!
How about fix error on big database by default?

**Comment by vitalyzhakov** [comment]
@joshp23 , hello!
We prepare new variant clear db by one iteration.

May be your merge it into main branch?

**Comment by vitalyzhakov** [comment]
@joshp23 , hello!
What solution for this pull request?

**Comment by joshp23** [comment]
I've been away at a new job, and quite busy. I have not had time to review this. Things appear to be relaxing a bit. If this continues, I will be able to have a look and potentially merge this. Thanks for your patience and work here.

**Comment by vitalyzhakov** [comment]
@joshp23 , hello!
It works for us during past 3 months.
Can your merge it to master?

**Comment by vitalyzhakov** [comment]
@joshp23 ?

**Comment by joshp23** [comment]
please resolve conflicts

**Comment by vitalyzhakov** [comment]
@joshp23 , hello!
Conflicts are resolved.

**Comment by joshp23** [comment]
I've been away from the bulk of my projects. I appreciate your patience and addition to this project. :)

**Pull request merged**
